# https://doc.rust-lang.org/cargo/reference/manifest.html
[package]
name = "hyperpi"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version = "4.5.57", features = ["derive"] }
colorgrad = "0.8"
crossterm = "0.29.0"
dashu = "0.4.2"
indicatif = "0.18.3"
inquire = "0.9.3"
miette = { version = "7.6.0", features = ["fancy"] }
num-bigint = "0.4.6"
num-traits = "0.2.19"
owo-colors = "4.2.3"
rayon = "1.11.0"
sha2 = "0.10.9"
strum = { version = "0.27.2", features = ["derive"] }
sysinfo = "0.38.1"
thiserror = "2.0.18"
